[project]
name = "ai-integration-learn"
version = "0.1.0"
description = "Learning about AI & integrations in python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "langchain>=0.3.25",
    "openai>=1.82.1",
    "pydantic-settings>=2.9.1",
]
